### PR TITLE
Feat/api/get channel follower

### PR DESCRIPTION
**Pull request by rosariop**
Added the Trovo GetChannelFollower (List) Api

### CODE REVIEW

**Comment by rosariop** [comment]
Is this repository active? If no I'd start a mirror.

**Comment by e3ndr** [comment]
> Is this repository active? If no I'd start a mirror.

Sorry, GitHub did not send me an email when this PR was made. 

Reviewing now.

**Comment by e3ndr** [comment]
Would you rather bring in your newer changed into the Repo or have this PR pulled in?

**Comment by rosariop** [comment]
I'd love to have this PR merged into your codebase.
The other changes i made on my fork will be discarded.

**Comment by rosariop** [comment]
Would you mind merging the changes into your master branch? I'm not allowed to 😞

**Pull request merged**
